/**
 * shared/openapi.js
 *
 * OpenAPI 3.1 YAML 생성기 — 서비스 그룹 배열을 받아 paths + components/schemas를
 * 포함한 완성된 YAML 문자열을 반환한다.
 */

import {
  parseBody,
  parseResp,
  methodName,
  reqDtoName,
  respDtoName,
} from './names.js';

/**
 * @param {Array<{service: string, endpoints: Array<{method,path,summary,body,response}>}>} groups
 * @param {string} catalogName — OpenAPI info.title에 쓰일 이름
 * @returns {string} YAML
 */
export function generateOpenApiYaml(groups, catalogName = 'Forge Protocol') {
  const schemas = {};
  const pathMap = {};

  // 1. 데이터 수집
  for (const grp of groups) {
    for (const ep of grp.endpoints) {
      const body = parseBody(ep.body);
      const resp = parseResp(ep.response);
      const rqd = reqDtoName(ep.method, ep.path);
      const rpd = respDtoName(ep.method, ep.path);

      if (body.kind === 'json' && body.fields.length && !schemas[rqd])
        schemas[rqd] = { fields: body.fields };
      if (resp.kind === 'json' && resp.fields.length && !schemas[rpd])
        schemas[rpd] = { fields: resp.fields };

      if (!pathMap[ep.path]) pathMap[ep.path] = {};
      pathMap[ep.path][ep.method.toLowerCase()] = {
        tag: grp.service,
        summary: ep.summary,
        operationId: methodName(ep.method, ep.path),
        hasId: ep.path.includes('{id}'),
        body,
        resp,
        rqd,
        rpd,
      };
    }
  }

  // 2. YAML 빌드
  const L = [];
  L.push(`openapi: "3.1.0"`);
  L.push(`info:`);
  L.push(`  title: "${catalogName} API"`);
  L.push(`  version: "1.0.0"`);
  L.push(
    `  description: "Generated by Forge Protocol — https://github.com/devsmith-kr/forge-protocol"`,
  );
  L.push(``);
  L.push(`tags:`);
  [...new Set(groups.map((g) => g.service))].forEach((t) => L.push(`  - name: "${t}"`));
  L.push(``);
  L.push(`paths:`);

  for (const [path, methods] of Object.entries(pathMap)) {
    L.push(`  "${path}":`);
    for (const [meth, op] of Object.entries(methods)) {
      L.push(`    ${meth}:`);
      L.push(`      summary: "${op.summary}"`);
      L.push(`      tags: ["${op.tag}"]`);
      L.push(`      operationId: "${op.operationId}"`);

      if (op.hasId) {
        L.push(`      parameters:`);
        L.push(`        - name: id`);
        L.push(`          in: path`);
        L.push(`          required: true`);
        L.push(`          schema:`);
        L.push(`            type: integer`);
        L.push(`            format: int64`);
      }

      if (op.body.kind === 'json' && op.body.fields.length) {
        L.push(`      requestBody:`);
        L.push(`        required: true`);
        L.push(`        content:`);
        L.push(`          application/json:`);
        L.push(`            schema:`);
        L.push(`              $ref: "#/components/schemas/${op.rqd}"`);
      } else if (op.body.kind === 'multipart') {
        L.push(`      requestBody:`);
        L.push(`        required: true`);
        L.push(`        content:`);
        L.push(`          multipart/form-data:`);
        L.push(`            schema:`);
        L.push(`              type: object`);
        L.push(`              properties:`);
        L.push(`                file:`);
        L.push(`                  type: string`);
        L.push(`                  format: binary`);
      }

      L.push(`      responses:`);
      if (op.resp.kind === 'none') {
        L.push(`        "204":`);
        L.push(`          description: "No Content"`);
      } else if (op.resp.kind === 'json' && op.resp.fields.length) {
        L.push(`        "${op.resp.status}":`);
        L.push(`          description: "Success"`);
        L.push(`          content:`);
        L.push(`            application/json:`);
        L.push(`              schema:`);
        L.push(`                $ref: "#/components/schemas/${op.rpd}"`);
      } else {
        L.push(`        "${op.resp.status}":`);
        L.push(`          description: "Success"`);
      }
      L.push(`        "400":`);
      L.push(`          description: "Bad Request"`);
      L.push(`        "401":`);
      L.push(`          description: "Unauthorized"`);
    }
  }

  // 3. Components/Schemas
  if (Object.keys(schemas).length > 0) {
    L.push(``);
    L.push(`components:`);
    L.push(`  schemas:`);
    for (const [name, schema] of Object.entries(schemas)) {
      L.push(`    ${name}:`);
      L.push(`      type: object`);
      L.push(`      properties:`);
      for (const f of schema.fields) {
        const typ = f === 'total' ? 'integer' : f === 'items' ? 'array' : 'string';
        if (f === 'items') {
          L.push(`        items:`);
          L.push(`          type: array`);
          L.push(`          items:`);
          L.push(`            type: object`);
        } else {
          L.push(`        ${f}:`);
          L.push(`          type: ${typ}`);
        }
      }
    }
  }

  return L.join('\n');
}
